apiVersion: v1
kind: Secret
metadata:
  name: registry-chrisjacob
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "ai-usage-svc.labels" . | nindent 4 }}
  annotations:
    "helm.sh/hook": pre-install
    "helm.sh/hook-weight": "-10"
    "helm.sh/hook-delete-policy": before-hook-creation
type: kubernetes.io/dockerconfigjson
data:
  .dockerconfigjson: {{ .Values.dockerhub_registry_config }}
